SSL improvement
Deveryware/ansible-haproxy pull request #59
Opened 2020-11-23 09:47 UTC by olo-dw

I think that the frontend ssl part is not smart. So I suggest this evolution.

* Fix of the extra spaces in the generated file
* Add ca-file to avoid the tricky include in the `options`
* Transform options from a string into an array.
* Add an example in the readme

2020-11-23 13:50 UTC, Aversiste requested changes

2020-11-23 13:50 UTC, Aversiste commented on README.md
> +SSL variables
S'il faut faire une section spécifique à TLS alors je préférerai nettement la formulation suivante:
```suggestion
TLS configuration
```

2020-11-23 13:50 UTC, Aversiste commented on README.md
> +        - "optional"
Premièrement `optional` est un paramètre de `verify` donc les mettre sur des lignes séparés n'a pas de sens et deuxièmement je suis contre exposer cette option plutôt que quelque chose de plus pertinent comme `force-tlsv12`.

2020-11-23 13:50 UTC, Aversiste commented on templates/frontend.cfg
> +    bind {{ bind }}{% if item.ssl is defined %}{% if item.ssl.cert is defined %} ssl{% for cert in item.ssl.cert %} crt {{ cert }}{% endfor %}{% if item.ssl.ca_file is defined %} ca-file {{ item.ssl.
Tu supprimes un espace en trop ici.

2020-11-24 13:51 UTC, olo-dw commented on README.md
> +        - "optional"
Quelles options seraient pertinentes de mettre en exemple pour expliquer les possibilités sans procéder à une rétro-ingénierie sur le _template_ ?

2020-11-26 10:23 UTC, closed without merging